<a href="https://colab.research.google.com/github/anupama0527/anupama0527.github.io/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
arr1=np.array(24)
print(arr1)
print(type(arr1))
print('dimension:',arr1.ndim)
print('shape:',arr1.shape)

24
<class 'numpy.ndarray'>
dimension: 0
shape: ()


In [ ]:
#1D array: to create 1D array and to specify the ;ayer of brackets

arr1=np.array([2,3,4])
print(arr1)
print('dimension:',arr1.ndim)
print('shape:',arr1.shape)

[2 3 4]
dimension: 1
shape: (3,)


In [ ]:
#2D array

arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1)

print('shape:',arr1.shape)print('dimension:',arr1.ndim)

[[1 2 3 4]
 [5 6 7 8]]
dimension: 2
shape: (2, 4)


In [ ]:
#create a @Dv array whose shape=(3,3)

arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)
print('dimension:',arr1.ndim)
print('shape:',arr1.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
dimension: 2
shape: (3, 3)


In [ ]:
import numpy as np
arr1=np.array([1,2,3,4])
print(arr1)
print("dimension:",arr1.ndim)
print("shape:",arr1.shape)

[1 2 3 4]
dimension: 1
shape: (4,)


In [ ]:
import numpy as np
arr1=np.array([[1,2,3],[6,7,8],[4,5,8],[2,3,4]])
print(arr1)
print(arr1.shape)

[[1 2 3]
 [6 7 8]
 [4 5 8]
 [2 3 4]]
(4, 3)


In [ ]:
# creating 3D array
arr3=np.array([[[1,2,3],[3,4,5],[5,6,7],[2,4,5]],[[1,2,3],[3,5,6],[5,6,7],[7,8,9]]])
print(arr3)
print("dimension:",arr3.ndim)
print("shape:",arr3.shape)

[[[1 2 3]
  [3 4 5]
  [5 6 7]
  [2 4 5]]

 [[1 2 3]
  [3 5 6]
  [5 6 7]
  [7 8 9]]]
dimension: 3
shape: (2, 4, 3)


In [ ]:
# creating 4D array
arr3=np.array([[[[1,2,3],[3,4,5],[5,6,7],[2,4,5]]] ])
print(arr3)
print("dimension:",arr3.ndim)
print("shape:",arr3.shape)

[[[[1 2 3]
   [3 4 5]
   [5 6 7]
   [2 4 5]]]]
dimension: 4
shape: (1, 1, 4, 3)


In [ ]:
arr1=np.array([1,2,3,4],ndmin=2)
print(arr1)
print(arr1.ndim)

[[1 2 3 4]]
2


In [ ]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
arr3=arr1+arr2
print(arr3)

[ 6  8 10 12]


In [ ]:
arr1=np.array([[1,2,3,4],[1,5,8,9]])
arr2=np.array([5,6,7,8])
arr3=arr1+arr2
print(arr3)

[[ 6  8 10 12]
 [ 6 11 15 17]]


In [ ]:
arr1=np.array([[1,2,3,4],[1,5,8,9]])
arr2=np.array([[5,6,7,8],[5,7,9,6]])
arr3=arr1+arr2
print(arr3)

[[ 6  8 10 12]
 [ 6 12 17 15]]


In [ ]:
#prg to create sum of all the items in 1D array

arr1=np.array([1,2,3,4])
sum=0
for i in arr1:
  sum+=i
print(sum)

10


In [ ]:
#accessing elements of 2D array

arr1=np.array([[1,2,3],[3,4,5]])
print(arr1[1][-2])
print(arr1[1,1:3])
print(arr1[0:2,0:2])

4
[4 5]
[[1 2]
 [3 4]]


In [ ]:
#accessing 3D array

arr3=np.array([[[1,2,3],[3,4,5]],[[5,6,7],[7,8,9]]])
print(arr3)
print(arr3[1][1][2])
print(arr3[0,1,0:2])
print(arr3[1,0,1])
print(arr3[0:2,1:2,0:2])

[[[1 2 3]
  [3 4 5]]

 [[5 6 7]
  [7 8 9]]]
9
[3 4]
6
[[[3 4]]

 [[7 8]]]


In [ ]:
#print the scalar values of array
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]])
for x in arr1:
  for y in x:
   print(y,end=' ')


1 2 3 4 5 6 

In [ ]:
#print the scalar values of array

import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in arr1:
  for y in x:
    for i in y:
      print(i,end=' ')
print( )      
print( arr1.shape)      

1 2 3 4 5 6 7 8 9 
(1, 3, 3)


In [ ]:
#nditer

import numpy as np
arr1=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for x in np.nditer(arr1):   #iteration
  print(x,end=" ")

1 2 3 4 5 6 7 8 9 

In [ ]:
#populate arrays with sequence of numbers
#arange()

arr1=np.arange(5,15,2)
print(arr1)
print("dimension:",arr1.ndim)
print("shape:",arr1.shape)

[ 5  7  9 11 13]
dimension: 1
shape: (5,)


In [ ]:
#populate array with random integer
#np.random.randint(low,high,size)

arr1=np.random.randint(low=10,high=20,size=(6))
print(arr1)

[12 17 14 10 18 16]


In [ ]:
arr1=np.random.randint(low=10,high=20,size=(6,3))
print(arr1)

[[18 16 10]
 [19 18 10]
 [11 10 11]
 [12 11 13]
 [12 13 14]
 [16 19 13]]


In [ ]:
arr1=np.random.randint(low=10,high=20,size=(6,3,5))
print(arr1)

[[[10 14 18 11 19]
  [17 17 13 17 11]
  [11 18 11 18 10]]

 [[16 18 19 13 15]
  [11 13 12 12 17]
  [13 14 15 19 18]]

 [[16 16 17 11 19]
  [14 10 17 16 15]
  [18 12 13 12 16]]

 [[11 11 12 15 18]
  [13 18 13 19 12]
  [12 13 13 18 11]]

 [[18 17 19 10 15]
  [16 16 16 12 16]
  [15 14 12 16 11]]

 [[15 15 16 12 13]
  [17 13 12 13 17]
  [10 10 12 18 15]]]


In [ ]:
arr1=np.random.randint(low=10,high=20,size=(6,3,2,2))
print(arr1)

[[[[13 10]
   [13 10]]

  [[13 15]
   [13 16]]

  [[12 16]
   [13 17]]]


 [[[16 14]
   [18 12]]

  [[14 11]
   [12 15]]

  [[12 12]
   [10 16]]]


 [[[14 12]
   [10 16]]

  [[14 10]
   [10 10]]

  [[10 19]
   [14 11]]]


 [[[14 15]
   [19 13]]

  [[18 10]
   [19 17]]

  [[11 10]
   [12 19]]]


 [[[16 10]
   [17 12]]

  [[11 18]
   [15 12]]

  [[12 11]
   [17 10]]]


 [[[12 16]
   [13 13]]

  [[16 17]
   [10 17]]

  [[14 15]
   [11 14]]]]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1+2)

[[3 4 5]
 [6 7 8]]


In [ ]:
arr1=np.array([[1,2,3],[4,5,6]])
print(arr1+2)
print(arr1*2)


[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]


create a linear dataset
create a simple dataset consisting og single and a label as follows
1. assign a sequence of integers from 6 to 20 to a numpy array named feature
2.


In [ ]:
feature=np.arange(6,21)
print(arr1)
label=(3)*feature+4
for i in range(16):
  np.label.append(i)
print(label)  


[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


AttributeError: ignored

In [ ]:
()